### ISSUE TITLE
I can't install the package!

### ISSUE THREAD

**Issue by MavLeague** [theusaf/mcfunction#24]
Hey, 
I've tried to install the package, but I can't. I've tried a few times.

**This Error occurred:**

> tree-sitter-mcfunction-lang@1.2.7 install C:\Users\Me\AppData\Local\Temp\apm-install-dir-20211118-15904-11h29xw.l9tbf\node_modules\mcfunction-lang\node_modules\tree-sitter-mcfunction-lang
> node-gyp rebuild

C:\Users\Me\AppData\Local\Temp\apm-install-dir-20211118-15904-11h29xw.l9tbf\node_modules\mcfunction-lang\node_modules\tree-sitter-mcfunction-lang>if not defined npm_config_node_gyp (node "C:\Users\Me\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Me\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\Me\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\Me\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Me\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\Me\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Users\\Me\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Me\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Me\AppData\Local\Temp\apm-install-dir-20211118-15904-11h29xw.l9tbf\node_modules\mcfunction-lang\node_modules\tree-sitter-mcfunction-lang
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Me\AppData\Local\Temp\apm-install-dir-20211118-15904-11h29xw.l9tbf\package.json'
npm WARN apm-install-dir-20211118-15904-11h29xw.l9tbf No description
npm WARN apm-install-dir-20211118-15904-11h29xw.l9tbf No repository field.
npm WARN apm-install-dir-20211118-15904-11h29xw.l9tbf No README data
npm WARN apm-install-dir-20211118-15904-11h29xw.l9tbf No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-mcfunction-lang@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-mcfunction-lang@1.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Me\.atom\.apm\_logs\2021-12-18T19_09_53_002Z-debug.log

**Comment by theusaf** [comment]
Thanks for the report. It looks like you might need to install Python on your computer to install it? I’ll look into the problem.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by MavLeague** [comment]
Thanks for your quick answer. (I'm sorry thant I'm answering so late!) I've installed python but it still doesnt work. It looks like it misses the right path. How can I tell the programm the right one?

**Comment by theusaf** [comment]
If you search for "environment variables" in the start menu and press enter, there should be an "environment variables" button, where you can edit the `Path` variable to specify where python is.

**Comment by belendrane** [comment]
Im having the exact same problem

**Comment by theusaf** [comment]
Thanks for the confirmation. I will try and look into this issue when I can.

**Comment by theusaf** [comment]
@belendrane 
I can install the package fine on my computer. If you are encountering this problem, ensure that Python is installed on your computer correctly.
